name: 0. Dev CI/CD
on: workflow_dispatch


jobs:

  CI:
    uses: WineServices/{{ cookiecutter.github_repo_name }}/.github/workflows/reusable-ci.yml@{{ cookiecutter.default_branch_name }}

  CD:
    uses: WineServices/{{ cookiecutter.github_repo_name }}/.github/workflows/reusable-cd.yml@{{ cookiecutter.default_branch_name }}

    with:
      region: "europe-west1"
      resource_name: "{{ cookiecutter.github_repo_name }}"
      env_name: "dev"
    {% raw %}
    secrets:
      project_id: ${{ secrets.PROD_GCP_PROJECT_ID }}
      sa_json_key: ${{ secrets.GCP_SA_KEY_JSON }}
    needs: CI
    {% endraw %}
