name: 1. Prod CI/CD
on: workflow_dispatch

{% raw %}
jobs:

  CI:
    if: github.ref == 'refs/heads/master'
    uses: WineServices/${{ github.event.repository.name }}/.github/workflows/reusable-ci.yml@{{ cookiecutter.default_branch_name }}

  CD:
    if: github.ref == 'refs/heads/master'
    uses: WineServices/${{ github.event.repository.name }}/.github/workflows/reusable-cd.yml@{{ cookiecutter.default_branch_name }}

    with:
      region: "europe-west1"
      resource_name: ${{ github.event.repository.name }}
      env_name: "prod"
    secrets:
      project_id: ${{ secrets.PROD_GCP_PROJECT_ID }}
      sa_json_key: ${{ secrets.GCP_SA_KEY_JSON }}
    needs: CI
{% endraw %}
