name: Reusable CI
on: workflow_call

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '{{ cookiecutter.python_version }}'
          architecture: 'x64'

      - name: install tox
        run: pip install tox

      - name: unit tests
        run: tox --recreate

      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          token: '{{ cookiecutter.codecov_token }}'
          verbose: true