name: Cloud run deployment
on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
      resource_name:
        required: true
        type: string
      env_name:
        required: true
        type: string

    secrets:
      project_id:
        required: true
      sa_json_key:
        required: true

env:
  PROJECT_ID: {% raw %}${{ secrets1.project_id }}
  SA_KEY_JSON: ${{ secrets2.sa_json_key }}{% endraw %}

jobs:

  cloud-run-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run: echo "Deploying {{ cookiecutter.gcp_service_type}} {% raw %}${{ inputs.resource_name }} into project ${{ env.PROJECT_ID }}  on region ${{ inputs.region }}{% endraw %}"
      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: {% raw %}${{ secrets.sa_json_key }}
          project_id: ${{ secrets.project_id }}{% endraw %}

      - name: setup gcloud
        uses: google-github-actions/setup-gcloud@v0

      - name: install beta
        run: gcloud components install beta
  {% if cookiecutter.gcp_service_type == 'cloud run' -%}
      {% raw %}
      - name: build
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/${{ inputs.resource_name }}:${{ inputs.env_name }}
      - name: deploy
        run: gcloud beta run deploy ${{ inputs.resource_name }} --image gcr.io/$PROJECT_ID/${{ inputs.resource_name }}:${{ inputs.env_name }} --platform managed --region ${{ inputs.region }}
      {% endraw %}
  {% elif cookiecutter.gcp_service_type == 'app engine' %}
      - name: deploy
        run: gcloud beta app deploy app.yaml --quiet --no-cache
  {%- endif %}
